interface handler {
    use jabratech:common/types.{response};
    use types.{calibrate-sabr-request, calibrate-sabr-response};

    get: func(request: calibrate-sabr-request) -> result<calibrate-sabr-response, response>;
}
