interface types {
    use jabratech:risk-engine/types.{sabr-greeks, sabr-volatility};
    record calibrate-sabr-request {
        currency: string,
        three-point-delta: f64,
    }
    
    record calibrate-sabr-response {
        code: s16,
        message: string,
        data: calibrate-sabr-data
    }

    record calibrate-sabr-data {
        instruments: list<sabr-calibrated-instrument>,
        sabr-greeks: sabr-greeks,
        volatility-summary: list<sabr-volatility>
    }

    record sabr-calibrated-instrument {
        expiry: string,
        forward-price: f64,
        market-vol: f64
    }
}
