interface types {

    record calibrate-sabr-request {
        currency: string,
        three-point-delta: f64,
    }
    
    record calibrate-sabr-response {
        code: s16,
        message: string,
        data: list<sabr-calibrated-instrument>
    }
    
    record sabr-calibrated-instrument {
        instrument-name: string,
        maturity-datetime: string,
        expiry: string,
        spot: f64,
        forward-price: f64,
        strike: f64,
        market-vol: f64
    }
    
    record calibrate-sabr-greeks-response {
        code: s16,
        message: string,
        data: list<sabr-calibrated-greek>
    }
    
    record sabr-calibrated-greek {
        name: string,
        description: option<string>,
        value: f64
    }
    
    record calibrate-sabr-volatility-summary-response {
        code: s16,
        message: string,
        data: list<sabr-calibrated-volatility>
    }
    
    record sabr-calibrated-volatility {
        expiry: string,
        forward-price: f64,
        market-vol: f64,
        risk-reversal: f64,
        butterfly: f64
    }
}